spring.application.name=SpringSecutiryApp
spring.datasource.url=jdbc:mysql://localhost:3306/security-app
spring.datasource.username=root
spring.datasource.password=Swift@5140
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
spring.security.user.name=fardeen
spring.security.user.password=Swift@5140

jwt.secretKey = scniusvbsdbvksncoisvewiubvewujsdkjcbsjbwevbjvwebvuwe

deploy.env=development
